server:
  port: 7070

spring:
  application:
    name: olive-gateway-server
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/carmel/uploads/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: do-login
          uri: lb://olive-auth-server
          predicates:
            - Path=/api/v1.0/doLogin
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1.0/doLogin, /api/v1/olive-login

        - id: olive-foundation-service
          uri: lb://olive-foundation-server
          predicates:
            - Path=/api/olive/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/olive/(?<segment>/?.*), /$\{segment}

#         - id: olive-foundation-service-resource
#           uri: lb://olive-foundation-server
#           predicates:
#             - Path=/css/**,/js/**,/images/**
#             - Method=GET
#           filters:
#             - RemoveRequestHeader=Cookie
#             - RewritePath=/(?<segment>/?.*), /$\{segment} 

#         - id: olive-static-resource-service
#           uri: lb://OLIVE-STATIC-RESOURCE-SERVER	
#           predicates:
#             - Path=/css/**,/js/**,/images/**,/profile/**
#             - Method=GET
#           filters:
#             - RemoveRequestHeader=Cookie
#             - RewritePath=/(?<segment>/?.*), /$\{segment} 



        - id: refresh-token
          uri: lb://olive-auth-server
          predicates:
            - Path=/api/v1.0/refreshToken
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1.0/refreshToken, /oauth/token
            
        - id: crm-service
          uri: lb://crm-server
          predicates:
            - Path=/crm/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/crm/(?<segment>/?.*), /$\{segment}           
      
#logging:
#  level:
#    root: trace    

#spring:
#  cloud:
#    gateway:
#      httpclient:
#        wiretap: true
#      httpserver:
#        wiretap: true

logging:
  level:
    reactor:
      netty: DEBUG
    org:
      springframework:
        cloud:
          gateway: DEBUG      
  file:
    name: ./logs/olive-gateway-server.log
    

